#!/bin/bash

set -o errexit
set -o nounset

SCRIPTDIR=$(dirname $0)

while getopts r:d:t:c: OPTLET; do
  case $OPTLET in
    d)
        OUTPUT_ROOT=$OPTARG
        ;;
    t)
        TYPEFACE=$OPTARG
        ;;
    r)
        RASTERISER=$OPTARG
        ;;
    c)
        CASES=$OPTARG
        ;;
    *)
        exit 2
        ;;
  esac
done

shift $((OPTIND-1))

mkdir -p $OUTPUT_ROOT

for i in $CASES/*.txt; do
    j=${i#${CASES}/}
    output_dir=$OUTPUT_ROOT/${j%.txt}
    mkdir -p $output_dir
    rm -f $output_dir/*
    $RASTERISER $i $output_dir $TYPEFACE
done
