name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_macos:
    name: Build MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install qt@6 boost
        env:
          HOMEBREW_NO_INSTALL_CLEANUP: 1
      - name: Build and package
        run: make dist
        working-directory: macos
      - name: Upload MacOS artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MacOS binaries
          path: bin/*
          retention-days: 1
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Native Tools Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build and package
        run: nmake dist
        working-directory: windows
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Windows binaries
          path: bin/*
          retention-days: 1
  package_and_release:
    needs: [build_macos, build_windows]
    name: Package up artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Download MacOS artifacts
        uses: actions/download-artifact@v2
        with:
          name: MacOS binaries
          path: alekhana
      - name: Download Windows artifacts
        uses: actions/download-artifact@v2
        with:
          name: Windows binaries
          path: alekhana
      - name: Zip up artifacts
        run: zip -r alekhana.zip alekhana
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: alekhana.zip
